//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzayad.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mzayad.Web.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your address..
        /// </summary>
        public static string AddressRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AddressRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias or Username.
        /// </summary>
        public static string AliasOrUsername {
            get {
                return ResourceManager.GetString("AliasOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your area..
        /// </summary>
        public static string AreaRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AreaRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar (select one).
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your block..
        /// </summary>
        public static string BlockRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BlockRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your building..
        /// </summary>
        public static string BuildingRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BuildingRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your notifications have been saved..
        /// </summary>
        public static string CategoryNotificationSaveMessage {
            get {
                return ResourceManager.GetString("CategoryNotificationSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your city..
        /// </summary>
        public static string CityRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CityRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Select.
        /// </summary>
        public static string ClickToSelect {
            get {
                return ResourceManager.GetString("ClickToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordMatchErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your country..
        /// </summary>
        public static string CountryRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CountryRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password..
        /// </summary>
        public static string CurrentPasswordValidationMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccountQuestion {
            get {
                return ResourceManager.GetString("DontHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully updated..
        /// </summary>
        public static string EditAccountNameSuccessMessage {
            get {
                return ResourceManager.GetString("EditAccountNameSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please a valid email address..
        /// </summary>
        public static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        public static string FirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        public static string HelloFirstName {
            get {
                return ResourceManager.GetString("HelloFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but the email address or password you have entered is incorrect..
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Prices.
        /// </summary>
        public static string ItemPrices {
            get {
                return ResourceManager.GetString("ItemPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jadda.
        /// </summary>
        public static string Jadda {
            get {
                return ResourceManager.GetString("Jadda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        public static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        public static string LastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username or email address..
        /// </summary>
        public static string NameOrEmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameOrEmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Password.
        /// </summary>
        public static string NeedPassword {
            get {
                return ResourceManager.GetString("NeedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have lost or forgotten your password please enter your email address in the form below and we will send you instructions on how to reset your password..
        /// </summary>
        public static string NeedPasswordInstructions {
            get {
                return ResourceManager.GetString("NeedPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Password?.
        /// </summary>
        public static string NeedPasswordQuestion {
            get {
                return ResourceManager.GetString("NeedPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Auctions by Category.
        /// </summary>
        public static string NewAuctionsByCategory {
            get {
                return ResourceManager.GetString("NewAuctionsByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can notify you when auctions are added with items in specific categories. To receive these notifications select your favorite categories:.
        /// </summary>
        public static string NewAuctionsByCategoryInstructions {
            get {
                return ResourceManager.GetString("NewAuctionsByCategoryInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password, it must be at least 6 characters..
        /// </summary>
        public static string NewPasswordValidationMessage {
            get {
                return ResourceManager.GetString("NewPasswordValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can opt into and subscribe to various notifications on the site, please use the options below to select which notifications you would like to receive..
        /// </summary>
        public static string NotificationsInstructions {
            get {
                return ResourceManager.GetString("NotificationsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select....
        /// </summary>
        public static string OptionLabel {
            get {
                return ResourceManager.GetString("OptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Items.
        /// </summary>
        public static string OrderItems {
            get {
                return ResourceManager.GetString("OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but we were unable to change your password. Please be sure you enter your current password correctly and try again..
        /// </summary>
        public static string PasswordChangeFailureMessage {
            get {
                return ResourceManager.GetString("PasswordChangeFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password, it must be at least 6 characters..
        /// </summary>
        public static string PasswordInvalidErrorMessage {
            get {
                return ResourceManager.GetString("PasswordInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        public static string PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Page.
        /// </summary>
        public static string ProfileURL {
            get {
                return ResourceManager.GetString("ProfileURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Users.
        /// </summary>
        public static string RegisteredUsers {
            get {
                return ResourceManager.GetString("RegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for free&lt;i class=&quot;fa fa-pad-left fa-angle-right&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string RegisterLinkText {
            get {
                return ResourceManager.GetString("RegisterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with Mzayad&apos;s &lt;a href=&quot;{0}&quot;&gt;terms and conditions&lt;/a&gt;..
        /// </summary>
        public static string RegistrationAgreementAcknowledgement {
            get {
                return ResourceManager.GetString("RegistrationAgreementAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, an error occurred registering your account: {0}..
        /// </summary>
        public static string RegistrationErrorMessage {
            get {
                return ResourceManager.GetString("RegistrationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Mzayad {0}! As soon as you are ready &lt;a class=&apos;alert-link&apos; href=&apos;#&apos;&gt;check out our upcoming bids&lt;i class=&apos;fa fa-pad-left fa-angle-right&apos;&gt;&lt;/i&gt;&lt;/a&gt;.
        /// </summary>
        public static string RegistrationWelcomeMessage {
            get {
                return ResourceManager.GetString("RegistrationWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, we cannot find a user account for this password reset attempt..
        /// </summary>
        public static string ResetPasswordCannotFindUserAccount {
            get {
                return ResourceManager.GetString("ResetPasswordCannotFindUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset email has been sent to &lt;strong&gt;{0}&lt;/strong&gt;, simply follow the instructions in the email to complete the reset..
        /// </summary>
        public static string ResetPasswordEmailSentAcknowledgement {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, the URL that you are attempting to use to reset your password has expired..
        /// </summary>
        public static string ResetPasswordExpiredTimestampException {
            get {
                return ResourceManager.GetString("ResetPasswordExpiredTimestampException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish resetting your password please enter your new password below..
        /// </summary>
        public static string ResetPasswordInstructions {
            get {
                return ResourceManager.GetString("ResetPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, the URL that you are attempting to use to reset your password is invalid..
        /// </summary>
        public static string ResetPasswordInvalidTokenException {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, the URL that you are attempting to use is missing one or more parameters..
        /// </summary>
        public static string ResetPasswordMissingParametersException {
            get {
                return ResourceManager.GetString("ResetPasswordMissingParametersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Instructions.
        /// </summary>
        public static string SendInstructions {
            get {
                return ResourceManager.GetString("SendInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string StateOrProvince {
            get {
                return ResourceManager.GetString("StateOrProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your state..
        /// </summary>
        public static string StateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your street..
        /// </summary>
        public static string StreetRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StreetRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Email.
        /// </summary>
        public static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username containing only letters and numbers..
        /// </summary>
        public static string UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking username....
        /// </summary>
        public static string UserNameValidateChecking {
            get {
                return ResourceManager.GetString("UserNameValidateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops sorry, username not available..
        /// </summary>
        public static string UserNameValidateError {
            get {
                return ResourceManager.GetString("UserNameValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great username!.
        /// </summary>
        public static string UserNameValidateIsValid {
            get {
                return ResourceManager.GetString("UserNameValidateIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your zip code..
        /// </summary>
        public static string ZipCodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ZipCodeRequiredErrorMessage", resourceCulture);
            }
        }
    }
}
