namespace Mazadaty.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ReplaceModelBaseWithEntityBase : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ActivityEvents", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ActivityEvents", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.ActivityEvents", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.ActivityEvents", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Addresses", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Addresses", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Addresses", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Addresses", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Auctions", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Auctions", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Auctions", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Auctions", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Bids", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Bids", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Bids", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Bids", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.SessionLogs", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SessionLogs", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.SessionLogs", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.SessionLogs", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Products", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Products", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Products", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Products", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Categories", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Categories", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Categories", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Categories", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ProductImages", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ProductImages", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.ProductImages", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.ProductImages", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ProductSpecifications", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ProductSpecifications", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.ProductSpecifications", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.ProductSpecifications", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Specifications", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Specifications", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Specifications", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Specifications", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Sponsors", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Sponsors", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Sponsors", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Sponsors", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.AutoBids", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.AutoBids", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.AutoBids", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.AutoBids", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Avatars", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Avatars", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Avatars", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Avatars", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CategoryNotifications", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.CategoryNotifications", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.CategoryNotifications", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.CategoryNotifications", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.EmailTemplates", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.EmailTemplates", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.EmailTemplates", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.EmailTemplates", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.IslamicCalendars", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.IslamicCalendars", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.IslamicCalendars", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.IslamicCalendars", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.KnetTransactions", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.KnetTransactions", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.KnetTransactions", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.KnetTransactions", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Orders", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Orders", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Orders", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Orders", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.OrderItems", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.OrderItems", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.OrderItems", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.OrderItems", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Subscriptions", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Subscriptions", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Subscriptions", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Subscriptions", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.OrderLogs", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.OrderLogs", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.OrderLogs", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.OrderLogs", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.SplashAds", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SplashAds", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.SplashAds", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.SplashAds", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.SubscriptionLogs", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SubscriptionLogs", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.SubscriptionLogs", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.SubscriptionLogs", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.TokenLogs", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.TokenLogs", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.TokenLogs", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.TokenLogs", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Trophies", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Trophies", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.Trophies", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.Trophies", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.UsersTrophies", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.UsersTrophies", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.UsersTrophies", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.UsersTrophies", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.WishLists", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.WishLists", "ModifiedUtc", c => c.DateTime());
            AddColumn("dbo.WishLists", "DeletedUtc", c => c.DateTime());
            AddColumn("dbo.WishLists", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
        }
        
        public override void Down()
        {
            DropColumn("dbo.WishLists", "RowVersion");
            DropColumn("dbo.WishLists", "DeletedUtc");
            DropColumn("dbo.WishLists", "ModifiedUtc");
            DropColumn("dbo.WishLists", "IsDeleted");
            DropColumn("dbo.UsersTrophies", "RowVersion");
            DropColumn("dbo.UsersTrophies", "DeletedUtc");
            DropColumn("dbo.UsersTrophies", "ModifiedUtc");
            DropColumn("dbo.UsersTrophies", "IsDeleted");
            DropColumn("dbo.Trophies", "RowVersion");
            DropColumn("dbo.Trophies", "DeletedUtc");
            DropColumn("dbo.Trophies", "ModifiedUtc");
            DropColumn("dbo.Trophies", "IsDeleted");
            DropColumn("dbo.TokenLogs", "RowVersion");
            DropColumn("dbo.TokenLogs", "DeletedUtc");
            DropColumn("dbo.TokenLogs", "ModifiedUtc");
            DropColumn("dbo.TokenLogs", "IsDeleted");
            DropColumn("dbo.SubscriptionLogs", "RowVersion");
            DropColumn("dbo.SubscriptionLogs", "DeletedUtc");
            DropColumn("dbo.SubscriptionLogs", "ModifiedUtc");
            DropColumn("dbo.SubscriptionLogs", "IsDeleted");
            DropColumn("dbo.SplashAds", "RowVersion");
            DropColumn("dbo.SplashAds", "DeletedUtc");
            DropColumn("dbo.SplashAds", "ModifiedUtc");
            DropColumn("dbo.SplashAds", "IsDeleted");
            DropColumn("dbo.OrderLogs", "RowVersion");
            DropColumn("dbo.OrderLogs", "DeletedUtc");
            DropColumn("dbo.OrderLogs", "ModifiedUtc");
            DropColumn("dbo.OrderLogs", "IsDeleted");
            DropColumn("dbo.Subscriptions", "RowVersion");
            DropColumn("dbo.Subscriptions", "DeletedUtc");
            DropColumn("dbo.Subscriptions", "ModifiedUtc");
            DropColumn("dbo.Subscriptions", "IsDeleted");
            DropColumn("dbo.OrderItems", "RowVersion");
            DropColumn("dbo.OrderItems", "DeletedUtc");
            DropColumn("dbo.OrderItems", "ModifiedUtc");
            DropColumn("dbo.OrderItems", "IsDeleted");
            DropColumn("dbo.Orders", "RowVersion");
            DropColumn("dbo.Orders", "DeletedUtc");
            DropColumn("dbo.Orders", "ModifiedUtc");
            DropColumn("dbo.Orders", "IsDeleted");
            DropColumn("dbo.KnetTransactions", "RowVersion");
            DropColumn("dbo.KnetTransactions", "DeletedUtc");
            DropColumn("dbo.KnetTransactions", "ModifiedUtc");
            DropColumn("dbo.KnetTransactions", "IsDeleted");
            DropColumn("dbo.IslamicCalendars", "RowVersion");
            DropColumn("dbo.IslamicCalendars", "DeletedUtc");
            DropColumn("dbo.IslamicCalendars", "ModifiedUtc");
            DropColumn("dbo.IslamicCalendars", "IsDeleted");
            DropColumn("dbo.EmailTemplates", "RowVersion");
            DropColumn("dbo.EmailTemplates", "DeletedUtc");
            DropColumn("dbo.EmailTemplates", "ModifiedUtc");
            DropColumn("dbo.EmailTemplates", "IsDeleted");
            DropColumn("dbo.CategoryNotifications", "RowVersion");
            DropColumn("dbo.CategoryNotifications", "DeletedUtc");
            DropColumn("dbo.CategoryNotifications", "ModifiedUtc");
            DropColumn("dbo.CategoryNotifications", "IsDeleted");
            DropColumn("dbo.Avatars", "RowVersion");
            DropColumn("dbo.Avatars", "DeletedUtc");
            DropColumn("dbo.Avatars", "ModifiedUtc");
            DropColumn("dbo.Avatars", "IsDeleted");
            DropColumn("dbo.AutoBids", "RowVersion");
            DropColumn("dbo.AutoBids", "DeletedUtc");
            DropColumn("dbo.AutoBids", "ModifiedUtc");
            DropColumn("dbo.AutoBids", "IsDeleted");
            DropColumn("dbo.Sponsors", "RowVersion");
            DropColumn("dbo.Sponsors", "DeletedUtc");
            DropColumn("dbo.Sponsors", "ModifiedUtc");
            DropColumn("dbo.Sponsors", "IsDeleted");
            DropColumn("dbo.Specifications", "RowVersion");
            DropColumn("dbo.Specifications", "DeletedUtc");
            DropColumn("dbo.Specifications", "ModifiedUtc");
            DropColumn("dbo.Specifications", "IsDeleted");
            DropColumn("dbo.ProductSpecifications", "RowVersion");
            DropColumn("dbo.ProductSpecifications", "DeletedUtc");
            DropColumn("dbo.ProductSpecifications", "ModifiedUtc");
            DropColumn("dbo.ProductSpecifications", "IsDeleted");
            DropColumn("dbo.ProductImages", "RowVersion");
            DropColumn("dbo.ProductImages", "DeletedUtc");
            DropColumn("dbo.ProductImages", "ModifiedUtc");
            DropColumn("dbo.ProductImages", "IsDeleted");
            DropColumn("dbo.Categories", "RowVersion");
            DropColumn("dbo.Categories", "DeletedUtc");
            DropColumn("dbo.Categories", "ModifiedUtc");
            DropColumn("dbo.Categories", "IsDeleted");
            DropColumn("dbo.Products", "RowVersion");
            DropColumn("dbo.Products", "DeletedUtc");
            DropColumn("dbo.Products", "ModifiedUtc");
            DropColumn("dbo.Products", "IsDeleted");
            DropColumn("dbo.SessionLogs", "RowVersion");
            DropColumn("dbo.SessionLogs", "DeletedUtc");
            DropColumn("dbo.SessionLogs", "ModifiedUtc");
            DropColumn("dbo.SessionLogs", "IsDeleted");
            DropColumn("dbo.Bids", "RowVersion");
            DropColumn("dbo.Bids", "DeletedUtc");
            DropColumn("dbo.Bids", "ModifiedUtc");
            DropColumn("dbo.Bids", "IsDeleted");
            DropColumn("dbo.Auctions", "RowVersion");
            DropColumn("dbo.Auctions", "DeletedUtc");
            DropColumn("dbo.Auctions", "ModifiedUtc");
            DropColumn("dbo.Auctions", "IsDeleted");
            DropColumn("dbo.Addresses", "RowVersion");
            DropColumn("dbo.Addresses", "DeletedUtc");
            DropColumn("dbo.Addresses", "ModifiedUtc");
            DropColumn("dbo.Addresses", "IsDeleted");
            DropColumn("dbo.ActivityEvents", "RowVersion");
            DropColumn("dbo.ActivityEvents", "DeletedUtc");
            DropColumn("dbo.ActivityEvents", "ModifiedUtc");
            DropColumn("dbo.ActivityEvents", "IsDeleted");
        }
    }
}
